export type { IAssetRepository } from './IAssetRepository'
export type { ITagRepository } from './ITagRepository'
export type { IGroupRepository } from './IGroupRepository'
export type { ISettingsRepository } from './ISettingsRepository'
export type { IUnityAssetLinkRepository } from './IUnityAssetLinkRepository'
export type { IAssetStoreLinkRepository } from './IAssetStoreLinkRepository'

export { assetRepository } from './DexieAssetRepository'
export { tagRepository } from './DexieTagRepository'
export { groupRepository } from './DexieGroupRepository'
export { settingsRepository } from './DexieSettingsRepository'
export { unityAssetLinkRepository } from './DexieUnityAssetLinkRepository'
export { assetStoreLinkRepository } from './DexieAssetStoreLinkRepository'
